apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SumanCloudOps25/cloud-native-java-platform'
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: java-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
